swagger: "2.0"

info:
  title: "foo API"
  version: "1.0"

basePath: /api

paths:
  /users:
    get:
      summary: get users
      description: |
        get all user ids
      # Hint: here we reference the actual Clojure function to call when this request comes in
      operationId: foo.handlers/get-all-users
      produces:
        - application/json
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Hello Tobi!"
              name:
                type: string
                example: "Tobi"
        default:
          description: error
    post:
      summary: add user
      description: |
        create a new user in the database
      # Hint: here we reference the actual Clojure function to call when this request comes in
      operationId: foo.handlers/add-user
      produces:
        - application/json
      parameters:
        - name: name
          in: query
          type: string
          required: true
          description: |
            Name of the new user.
        - name: age
          in: query
          type: integer
          required: true
          description: |
            Age of the person
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              message:
                type: string
                example: "created"
        default:
          description: error
  /users/{id}:
    get:
      summary: get user by id
      description: |
        get user by id
      # Hint: here we reference the actual Clojure function to call when this request comes in
      operationId: foo.handlers/get-user
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          type: string
          required: true
          description: |
            id of the user
      responses:
        200:
          description: success
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Hello Tobi!"
              name:
                type: string
                example: "Tobi"
        default:
          description: error
